description: "Minimal Ceph deployment for LXD"
relations:
- - ceph-osd:mon
  - ceph-mon:osd
- [ceph-radosgw, ceph-mon]
series: xenial
applications:
  ceph-mon:
    annotations:
      gui-x: '750'
      gui-y: '500'
    charm: cs:ceph-mon-24
    num_units: 1
    options:
      monitor-count: 1
      source: cloud:xenial-queens
  ceph-osd:
    annotations:
      gui-x: '1000'
      gui-y: '500'
    charm: cs:ceph-osd-261
    num_units: 3
    options:
      osd-devices: "/srv/osd1 /srv/osd2 /srv/osd3"
      use-direct-io: False
      source: cloud:xenial-queens
  ceph-radosgw:
    charm: cs:ceph-radosgw
    num_units: 1
    options:
      source: cloud:xenial-queens
